apiVersion: v1
kind: Service
metadata:
  name: financial-backend
  namespace: financial-app
spec:
  type: ClusterIP
  selector: { app: financial-backend }
  ports: [{ port: 3000, targetPort: http, name: http }]
