apiVersion: v1
kind: Service
metadata:
  name: financial-frontend
  namespace: financial-app
spec:
  type: ClusterIP
  selector: { app: financial-frontend }
  ports: [{ port: 80, targetPort: http, name: http }]
