import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AreaChart, Area, PieChart, Pie, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownCircle, ArrowUpCircle, LayoutDashboard, List, LogOut, Plus, Search, WalletCards, X, Loader2, Trash2 } from 'lucide-react';
import './styles.css';

type Category={id:number;name:string;color:string;type:string}; type Transaction={id:number;amount:string;date:string;type:'income'|'expense';description:string;status:string;category_name?:string;category_color?:string};
const API=import.meta.env.VITE_API_URL || '/api';
const money=(v:number|string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));
const formatDate=(value:string)=>{
  const dateOnly=value.slice(0,10);
  return new Date(`${dateOnly}T12:00:00`).toLocaleDateString('pt-BR');
};
const request=async(path:string,token:string,options:RequestInit={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Não foi possível concluir a ação');return r.status===204?null:r.json()};

function App(){
 const [token,setToken]=useState(localStorage.getItem('fc_token')||''),[view,setView]=useState<'dashboard'|'transactions'>('dashboard'),[dashboard,setDashboard]=useState<any>(),[transactions,setTransactions]=useState<Transaction[]>([]),[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(false),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[filters,setFilters]=useState({search:'',type:'',from:'',to:''});
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3200)};
 const load=async()=>{if(!token)return;setLoading(true);try{const [d,c,t]=await Promise.all([request('/dashboard',token),request('/categories',token),request('/transactions?limit=20'+(filters.search?`&search=${encodeURIComponent(filters.search)}`:'')+(filters.type?`&type=${filters.type}`:'')+(filters.from?`&from=${filters.from}`:'')+(filters.to?`&to=${filters.to}`:''),token)]);setDashboard(d);setCategories(c);setTransactions(t.items)}catch(e:any){notify(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[token,filters.type,filters.from,filters.to]);
 if(!token)return <Login onLogin={(t)=>{localStorage.setItem('fc_token',t);setToken(t)}}/>;
 const s=dashboard?.summary||{balance:0,income:0,expense:0};
 return <div className="shell"><aside><div className="brand"><WalletCards/> <span>Fin<span>Control</span></span></div><nav><button className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')}><LayoutDashboard/> Dashboard</button><button className={view==='transactions'?'active':''} onClick={()=>setView('transactions')}><List/> Transações</button></nav><div className="sidebar-footer"><span className="demo-dot"/> Ambiente demo<button className="logout" onClick={()=>{localStorage.removeItem('fc_token');setToken('')}}><LogOut/> Sair</button></div></aside><main><header><div><p className="eyebrow">VISÃO GERAL</p><h1>{view==='dashboard'?'Olá, como estão suas finanças?':'Transações'}</h1></div><button className="primary" onClick={()=>setModal(true)}><Plus/> Nova transação</button></header>{loading&&!dashboard?<div className="loader"><Loader2/> Carregando dados...</div>:view==='dashboard'?<Dashboard summary={s} data={dashboard}/>:<Transactions rows={transactions} filters={filters} setFilters={setFilters} onRefresh={load} token={token}/>}</main>{modal&&<TransactionModal categories={categories} onClose={()=>setModal(false)} onSave={async(data)=>{await request('/transactions',token,{method:'POST',body:JSON.stringify(data)});setModal(false);notify('Transação adicionada com sucesso');load()}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Login({onLogin}:{onLogin:(x:string)=>void}){const [email,setEmail]=useState('demo@financeiro.app'),[password,setPassword]=useState('demo123'),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login"><div className="login-card"><div className="brand dark"><WalletCards/> Fin<span>Control</span></div><h1>Seu dinheiro, sob controle.</h1><p>Acesse o ambiente demonstrativo.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);onLogin(d.token)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<small className="error">{error}</small>}<button className="primary wide" disabled={busy}>{busy?'Entrando...':'Entrar na demonstração'}</button></form><small>Credenciais pré-preenchidas: demo@financeiro.app / demo123</small></div></div>}
function Dashboard({summary,data}:{summary:any;data:any}){const cards=[['Saldo atual',summary.balance,WalletCards,'violet'],['Receitas do mês',summary.income,ArrowUpCircle,'green'],['Despesas do mês',summary.expense,ArrowDownCircle,'red']];return <><section className="cards">{cards.map(([title,value,Icon,color]:any)=><article className="card" key={title}><div><p>{title}</p><strong>{money(value)}</strong><small>{title==='Saldo atual'?'Resultado do mês':'Consolidado no período'}</small></div><i className={color}><Icon/></i></article>)}</section><section className="charts"><article className="chart-card wide-chart"><div><h2>Fluxo de caixa</h2><p>Receitas e despesas nos últimos seis meses</p></div><div className="chart"><ResponsiveContainer><AreaChart data={data?.trend||[]}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#22c55e" stopOpacity=".28"/><stop offset="1" stopColor="#22c55e" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="period" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`R$${v/1000}k`} tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>money(v)}/><Area type="monotone" dataKey="income" name="Receitas" stroke="#22c55e" fill="url(#income)" strokeWidth={3}/><Area type="monotone" dataKey="expense" name="Despesas" stroke="#ef4444" fill="none" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></article><article className="chart-card pie-card"><h2>Despesas por categoria</h2><p>Distribuição do mês</p><div className="pie"><ResponsiveContainer><PieChart><Pie data={(data?.expensesByCategory||[]).filter((x:any)=>+x.amount>0)} dataKey="amount" nameKey="name" innerRadius="57%" outerRadius="80%" paddingAngle={4}>{(data?.expensesByCategory||[]).map((x:any)=><Cell key={x.id} fill={x.color}/>)}</Pie><Tooltip formatter={(v:any)=>money(v)}/></PieChart></ResponsiveContainer></div><div className="legend">{(data?.expensesByCategory||[]).filter((x:any)=>+x.amount>0).slice(0,4).map((x:any)=><span key={x.id}><b style={{background:x.color}}/> {x.name}</span>)}</div></article></section></>}
function Transactions({rows,filters,setFilters,onRefresh,token}:{rows:Transaction[];filters:any;setFilters:any;onRefresh:()=>void;token:string}){return <><section className="filters"><div className="search"><Search/><input aria-label="Buscar por descrição" placeholder="Buscar por descrição..." value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} onKeyDown={e=>e.key==='Enter'&&onRefresh()}/></div><select aria-label="Filtrar por tipo" value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">Todos os tipos</option><option value="income">Receitas</option><option value="expense">Despesas</option></select><input aria-label="Data inicial" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input aria-label="Data final" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></section><section className="table-card"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th>Status</th><th>Valor</th><th/></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><strong>{t.description}</strong><small>{t.type==='income'?'Receita':'Despesa'}</small></td><td><span className="category"><b style={{background:t.category_color||'#94a3b8'}}/>{t.category_name||'Sem categoria'}</span></td><td>{formatDate(t.date)}</td><td><span className={`status ${t.status}`}>{t.status==='paid'?'Pago':'Pendente'}</span></td><td className={t.type}>{t.type==='income'?'+':'-'} {money(t.amount)}</td><td><button aria-label="Excluir transação" title="Excluir transação" className="icon-button" onClick={async()=>{if(confirm('Excluir esta transação?')){await request(`/transactions/${t.id}`,token,{method:'DELETE'});onRefresh()}}}><Trash2/></button></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="empty">Nenhuma transação encontrada.</td></tr>}</tbody></table></section></>}
function TransactionModal({categories,onClose,onSave}:{categories:Category[];onClose:()=>void;onSave:(x:any)=>Promise<void>}) {
 const [form,setForm]=useState<any>({type:'expense',amount:'',date:new Date().toISOString().slice(0,10),description:'',status:'paid',category_id:''});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const update=(key:string,value:string)=>setForm({...form,[key]:value});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await onSave({...form,amount:+form.amount,category_id:+form.category_id||null});}catch(err:any){setError(err.message);setBusy(false);}};
 return <div className="overlay"><form className="modal" onSubmit={submit}>
  <button aria-label="Fechar" title="Fechar modal" className="close" type="button" onClick={onClose}><X/></button><h2>Nova transação</h2><p>Registre uma receita ou despesa.</p>
  <div className="type-toggle"><button type="button" className={form.type==='expense'?'selected expense':''} onClick={()=>update('type','expense')}>Despesa</button><button type="button" className={form.type==='income'?'selected income':''} onClick={()=>update('type','income')}>Receita</button></div>
  <label>Descrição<input required value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Ex.: Mercado semanal"/></label>
  <div className="row"><label>Valor<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e=>update('amount',e.target.value)} placeholder="0,00"/></label><label>Data<input required type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label></div>
  <label>Categoria<select value={form.category_id} onChange={e=>update('category_id',e.target.value)}><option value="">Sem categoria</option>{categories.filter(c=>c.type==='both'||c.type===form.type).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{error&&<small className="error">{error}</small>}<button className="primary wide" disabled={busy}>{busy?'Salvando...':'Salvar transação'}</button>
 </form></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
